# Generated by Django 5.1.5 on 2025-01-30 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=250)),
                ("precio", models.FloatField()),
                ("descripcion", models.CharField(max_length=500)),
                ("costo", models.FloatField()),
            ],
        ),
    ]
